name: sync_client
description: Mobile and Desktop device application for automatically uploading image, video and audio files
publish_to: 'none'

version: 0.0.1+alpha

environment:
  sdk: '>=3.2.0 <5.0.0'

# Upgrade your package dependencies to the latest versions - `flutter pub upgrade --major-versions`.
# Dependencies with newer versions: `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  file_picker: ^8.0.6
  device_info_plus: ^10.1.0
  http_parser: ^4.0.2
  mime: ^1.0.4
  path: ^1.8.3
  http: ^1.1.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  go_router: ^14.2.0
  realm: ^3.1.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  # Lint rules are defined in `analysis_options.yaml`.
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true

  assets:
     - images/

flutter_icons:
  image_path: "images/mobi-sync.png"
  android: true
  ios: true