name: sync_client
description: Mobile and Desktop device application for automatically uploading image, video and audio files
publish_to: 'none'

version: 0.0.1+alpha

environment:
  sdk: '>=3.1.3 <4.0.0'

# Upgrade your package dependencies to the latest versions - `flutter pub upgrade --major-versions`.
# Dependencies with newer versions: `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  file_picker: ^6.1.1
  device_info_plus: ^9.1.1
  http_parser: ^4.0.2
  mime: ^1.0.4
  path: ^1.8.3
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lint rules are defined in `analysis_options.yaml`.
  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  assets:
     - images/
