name: Sync_Client

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
      group: ${{ github.head_ref || (github.workflow && github.run_id) }}
      cancel-in-progress: true

env:
  SYNC_SERVER_URL: ${{ vars.SYNC_SERVER_URL }}

jobs:
  UnitTests:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout source
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze

      - name: Run unit tests
        run: flutter test --coverage

  IntegrationTests:
    runs-on: ubuntu-latest
    needs: UnitTests

    steps:
      - name : Checkout source
        uses: actions/checkout@v3

      - name: Setup GTK
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libgtk-3-dev xvfb

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: dart pub get

      - name: Run integration tests
        run: xvfb-run flutter test integration_test