name: Sync_Client_Unit_Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
      group: ${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

env:
  SYNC_SERVER_URL: ${{ vars.SYNC_SERVER_URL }}
jobs:
  UnitTests:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout source
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze

      - name: Run unit tests
        run: flutter test --coverage